<a href="https://colab.research.google.com/github/ShilpaVasista/PDA---23CSE313/blob/main/Module_2_Part_III.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Data Structures**
- The different data structures
included in Python are array, list, tuple, and dictionary.
- The difference between an array and a
list is that an array is a collection of similar data types (homogeneous), whereas a list can be a
collection of different data types (heterogeneous).
- While array and list can be modified by adding, deleting, and modifying the existing elements, it is not possible to modify the tuple. A
dictionary is a unique data structure generally not available in programming languages and is
represented as key–value pair.

## **3.1 Lists**
- A list is a collection of objects that represents an ordered sequence of data.
- A list is a collection similar to a string, which is a collection of characters.
- Unlike a string (which only contains characters), a list can hold elements of different data types (e.g., integers, strings, floats, etc.).

###**Creating a List**
- A list is created by using square brackets and like any other variable, a list variable must be assigned before it is used.

In [ ]:
print("Please enter five decimal numbers:")
total = 0

# Creating an empty list
firstlist = []

# Using for loop to take input of numbers and storing in the list
for i in range(5):
    value = float(input("Enter number " + str(i + 1) + ": "))
    firstlist.append(value)  # Append value to the list
    total += value  # Add value to total

# Displaying the numbers using for loop
print("The numbers entered are:")
for num in firstlist:
    print(num, end=" ")

# Displaying the sum of all elements in the list
print()  # Print a new line
print("The sum of numbers is:", total)

Please enter five decimal numbers:
Enter number 1: 1
Enter number 2: 2
Enter number 3: 3
Enter number 4: 4
Enter number 5: 5
The numbers entered are:
1.0 2.0 3.0 4.0 5.0
The sum of numbers is: 15.0

- A list can be created without explicitly listing all elements.
- The range() function generates a sequence of integers.
- The output of print(a) where a = range(0, 5) displays as range(0, 5) instead of printing the integers 0 to 4.
- The list() function can convert the sequence generated by range() into a list.
- The object returned by range() is not a list; it is a range object.
- To obtain a list from a range, you must use the list() function.

In [ ]:
# Creating a list of positive integers with default interval
print(range(12,19))

list1 = list(range(12, 19))
print("First List:\n", list1)

# Creating a list of negative to positive integers with default interval
list2 = list(range(-3, 5))
print("Second List:\n", list2)

# Creating a list of numbers in descending order with specified interval
list3 = list(range(30, -10, -2))
print("Third List:\n", list3)

# Creating a list of numbers in ascending order with specified interval
list4 = list(range(0, 300, 50))
print("Fourth List:\n", list4)

range(12, 19)
First List:
 [12, 13, 14, 15, 16, 17, 18]
Second List:
 [-3, -2, -1, 0, 1, 2, 3, 4]
Third List:
 [30, 28, 26, 24, 22, 20, 18, 16, 14, 12, 10, 8, 6, 4, 2, 0, -2, -4, -6, -8]
Fourth List:
 [0, 50, 100, 150, 200, 250]

It is also possible to concatenate two lists together in a single list. The plus (+) operator concatenates lists in the same way as it concatenates strings

In [ ]:
# Program for showing List concatenation

list5 = [11, 22, 32, 40, 50]
list6 = [31, 5, 30, 20]

# Displaying the type of list5 and list6
print("The class of list5 is:", type(list5))
print("The class of list6 is:", type(list6))

# Concatenation of two lists into one single list
list7 = list5 + list6  # Concatenating the two lists

# Displaying the new concatenated list
print("The new list is:\n", list7)

# Displaying the type of the new list
print("The class of list7 is:", type(list7))

The class of list5 is: <class 'list'>
The class of list6 is: <class 'list'>
The new list is:
 [11, 22, 32, 40, 50, 31, 5, 30, 20]
The class of list7 is: <class 'list'>

###**Accessing List Elements**
- List elements are accessed using square brackets with an index.
- Indexing and slicing are the concepts used for accessing list items.
- In the expression userlist[k], k is referred to as an index or subscript.
- Unlike mathematical conventions, list indexing in Python starts at 0.
- The first element of a list is at position 0, making it represented as userlist[0].
- If there are n elements in a list, the last element is accessed using userlist[n - 1].

In [ ]:
# Program for accessing numbers of a list
list8 = [15, -3, 10, 14, -55]

# Using a for loop to display all numbers of the list
for num in range(0, 5):
    print("The", num + 1, "number is:", list8[num])  # Accessing elements with positive indexing

# Using a for loop and negative indexing to display all numbers of the list
print("Using Negative indexing")
for val in range(-1, -6, -1):
    print("The number is:", list8[val])  # Accessing elements with negative indexing

The 1 number is: 15
The 2 number is: -3
The 3 number is: 10
The 4 number is: 14
The 5 number is: -55
Using Negative indexing
The number is: -55
The number is: 14
The number is: 10
The number is: -3
The number is: 15

- A list in Python can contain elements of different data types, making it non-homogeneous.
- It is possible to have lists within other lists (nested lists).
- To access an item in a nested list, use two sets of square brackets.

Example: userlist[a][b] accesses an item where:
- a is the index of the outer list.
- b is the index of the inner (nested) list.

In [ ]:
# Program for accessing elements of a heterogeneous list

list9 = [12.56, -367, ["India", "USA", "UK", "China"], "countries"]

# Using for loop to display all the elements of the list
for val in range(0, 4):
    print("The element", val + 1, "is:", list9[val])  # Accessing elements of the main list

# Accessing individual items of the nested list
for x in range(0, 4):
    print("List item of nested list is:", list9[2][x])  # Accessing elements of the nested list
print(list9[5])

The element 1 is: 12.56
The element 2 is: -367
The element 3 is: ['India', 'USA', 'UK', 'China']
The element 4 is: countries
List item of nested list is: India
List item of nested list is: USA
List item of nested list is: UK
List item of nested list is: China

IndexError: list index out of range

Few Things to Note:
- It should be noted that if the starting argument is absent, the index is considered to be 0 (start of
the list) for the starting argument.
- If end argument is absent, the ending argument is considered
as length of list −1 (end of list).

In [4]:
# Program for showing the use of list slicing

list10 = [0, 100, 200, 300, 400, 500, 600, 700, 800, 900]

# Elements between the starting and ending index are displayed
print("Elements from third index and before sixth index:", list10[3:6])

# An empty list is returned if user enters a negative value for index (with improper range)
print("Elements starting from negative index not shown:", list10[-4:2])

# The start value defaults to 0 if the begin argument is missing
print("Elements from starting and before third index:", list10[:3])

# If the end value is missing, it defaults to the length of the list
print("Elements from fifth index and till last index:", list10[5:])

# End value greater than length of list is considered the length of the list
print("Elements from sixth index and till a large index:", list10[6:12])

# The starting index greater than the ending index returns an empty list
print("Starting from higher and ending at lower index:", list10[4:0])

Elements from third index and before sixth index: [300, 400, 500]
Elements starting from negative index not shown: [600, 500, 400, 300]
Elements from starting and before third index: [0, 100, 200]
Elements from fifth index and till last index: [500, 600, 700, 800, 900]
Elements from sixth index and till a large index: [600, 700, 800, 900]
Starting from higher and ending at lower index: []

- It is possible to change the existing elements in a list by specifying the index number along with
new value.

In [ ]:
# Program for modifying the existing list element.

list11 = [100, 200, 300, 400, 500, 600, 700]

print("The original list is:\n", list11)

# Modifying elements in the list
list11[1] = 110
list11[4] = 120

# Displaying the modified list
print("The new list after modification is:\n", list11)

The original list is:
 [100, 200, 300, 400, 500, 600, 700]
The new list after modification is:
 [100, 110, 300, 400, 120, 600, 700]

- You can modify a list by removing elements or adding a sub-range of elements.
- This can be done using slice assignment, where you specify a sub-range of the list.
- The slicing expression is placed on the left side of the assignment operator to modify the list.

In [ ]:
# Program for adding, removing, and modifying list items using slicing.

list12 = [[168, 387], "JAVA", 14, 35, 77, "c"]
print("Original list is:\n", list12)

# Replacing multiple elements in the list
list12[2:4] = ['MP', 'UP', 'AP']
print("List after replacing multiple elements is:\n", list12)

# Inserting multiple items at the third index
list12[3:3] = [12, 13, 14]
print("List after inserting elements at index 3:\n", list12)

# Deleting some elements from the list
list12[3:5] = []
print("List after removal of items is:\n", list12)

Original list is:
 [[168, 387], 'JAVA', 14, 35, 77, 'c']
List after replacing multiple elements is:
 [[168, 387], 'JAVA', 'MP', 'UP', 'AP', 77, 'c']
List after inserting elements at index 3:
 [[168, 387], 'JAVA', 'MP', 12, 13, 14, 'UP', 'AP', 77, 'c']
List after removal of items is:
 [[168, 387], 'JAVA', 'MP', 14, 'UP', 'AP', 77, 'c']

###**Functions for List**
Different in-built functions for performing operations efficiently on lists exist in Python. These
functions include insert(), copy(), len(), count(), index(), max(), min(), remove(),
append(), sort(), sum(), etc.

In [5]:
# Program for demonstrating functions on lists
mylist = [100, 100, 400, 200, 300, 300, 500, 600, 700, 100]

# The max() function determines the maximum number in a list.
print("Maximum number in the list is:", max(mylist))

# The min() function determines the minimum number in a list.
print("Minimum number in the list is:", min(mylist))

# The len() function determines the length of the list.
print("Length of the new list is:", len(mylist))

# The count() returns the number of times a given element appears in a list.
print("Number of times 100 occurred in list is:", mylist.count(100))

# The index() function returns the lowest index of an element in a list.
print("First position of element 200 in list is:", mylist.index(200))

# The remove() function removes the first occurrence of an element from the list.
mylist.remove(400)
print("New list after removing element 400 is:\n", mylist)

# The append() function adds a new element to the end of the list.
mylist.append(800)
print("New list after adding element 800 is:\n", mylist)

# The insert() function inserts a new element before the element at a given index.
mylist.insert(4, 900)
print("New list after adding element 900 at index 4 is:\n", mylist)

# The pop() function returns the element at a specified index.
# If the argument is not mentioned, the function returns the last element.
print("Last element of the list is:", mylist.pop())
print("Third element of the list is:", mylist.pop(2))

# The reverse() function physically reverses the elements in the list.
mylist.reverse()
print("Reversed list is:\n", mylist)

# The sorted() function sorts the elements of the list in ascending order without modifying the original list.
print("Sorted list without modifying the original list is:\n", sorted(mylist))
print("Original list is:\n", mylist)

# The sort() function sorts the elements of the list in ascending order and modifies the list.
mylist.sort()
print("Sorted list after modifying the list using sort() is:\n", mylist)

# The copy() function creates a new list similar to the original list.
mylist2 = mylist.copy()

# The extend() function helps to add a list to the existing list.
templist = [1200, 1400, 1600]
mylist2.extend(templist)
print("Extended new list is:\n", mylist2)

# The clear() function helps to clear the list by deleting all elements.
mylist2.clear()
print("New list after clearing all elements is:", mylist2)

Maximum number in the list is: 700
Minimum number in the list is: 100
Length of the new list is: 10
Number of times 100 occurred in list is: 3
First position of element 200 in list is: 3
New list after removing element 400 is:
 [100, 100, 200, 300, 300, 500, 600, 700, 100]
New list after adding element 800 is:
 [100, 100, 200, 300, 300, 500, 600, 700, 100, 800]
New list after adding element 900 at index 4 is:
 [100, 100, 200, 300, 900, 300, 500, 600, 700, 100, 800]
Last element of the list is: 800
Third element of the list is: 200
Reversed list is:
 [100, 700, 600, 500, 300, 900, 300, 100, 100]
Sorted list without modifying the original list is:
 [100, 100, 100, 300, 300, 500, 600, 700, 900]
Original list is:
 [100, 700, 600, 500, 300, 900, 300, 100, 100]
Sorted list after modifying the list using sort() is:
 [100, 100, 100, 300, 300, 500, 600, 700, 900]
Extended new list is:
 [100, 100, 100, 300, 300, 500, 600, 700, 900, 1200, 1400, 1600]
New list after clearing all elements is: []

**Repeating elements using “*” operator:**

The list elements can be repeated using the “ * ”
operator.

In [1]:
# Program for repeating list elements using the "*" operator

# Repeating a list directly in the print statement
print("Repetition of list elements:\n", [10, 20, 30, 40] * 3)

# Repeating the list by specifying the list name
mylist3 = [10, 20, 30]
print("Repetition of an existing list:\n", mylist3 * 4)

# Repeating a list before using the print statement
newlist = mylist3 * 2
print("Displaying new list:\n", newlist)

Repetition of list elements:
 [10, 20, 30, 40, 10, 20, 30, 40, 10, 20, 30, 40]
Repetition of an existing list:
 [10, 20, 30, 10, 20, 30, 10, 20, 30, 10, 20, 30]
Displaying new list:
 [10, 20, 30, 10, 20, 30]

**Determining existence of list item using “in” operator:**

The “in” operator helps us to
determine whether a particular element is present in the list or not.

In [2]:
# Determine whether a particular item exists/does not exist using "in"

mylist4 = [20, 40, 60, 80, 100, 120]

# Check if an element exists in the list
print("The element 50 exists in the list:", 50 in mylist4)
print("The element 60 exists in the list:", 60 in mylist4)

The element 50 exists in the list: False
The element 60 exists in the list: True

#**3.2 Tuples**#
- A tuple is a collection of objects separated by commas inside parentheses.
- Tuples are immutable, meaning their elements cannot be modified.
- Lists are mutable, allowing modification of their elements.
- Tuples are generally used when data does not require modification and only retrieval is needed.
- Tuples are represented by parentheses ( ), while lists are represented by square brackets [ ].

##Creating a Tuple
- Tuples are created using the tuple() function or by writing elements separated by commas inside parentheses.
- An empty tuple is created using empty parentheses: ().
- To create a tuple with a single item, a comma must be placed after the item, e.g., mytuple = (item,). Without the comma, it is treated as a regular expression wrapped in parentheses.
- Parentheses are optional when creating tuples, so mytuple = 10, 20, 30 is equivalent to mytuple = (10, 20, 30).
- Parentheses are recommended for better readability and application.
- Tuple elements, like list elements, can be heterogeneous, meaning they can contain different data types.

In [3]:
# Program to create tuples using different methods

# Creating an empty tuple
mytuple1 = ()
print(type(mytuple1))
print("An empty tuple is:", mytuple1)

# Creating a one-element tuple by adding a comma at the end
mytuple2 = (542,)
print("A tuple with a single element is:\n", mytuple2)

# Creating a tuple with multiple elements
mytuple3 = (10, 20, 30, 40, 50)
print("A tuple with multiple elements is:\n", mytuple3)

# Creating a tuple using the tuple() and range() functions
mytuple4 = tuple(range(5, 60, 10))
print("A tuple created using range() function is:\n", mytuple4)

# Creating a tuple from a list
mylist5 = [0, 100, 200, 300, 400]
mytuple5 = tuple(mylist5)
print("A tuple created from a list is:\n", mytuple5)

# Concatenation of tuples to create a new tuple
mytuple6 = mytuple5 + mytuple4
print("A tuple created by concatenating two tuples is:\n", mytuple6)

<class 'tuple'>
An empty tuple is: ()
A tuple with a single element is:
 (542,)
A tuple with multiple elements is:
 (10, 20, 30, 40, 50)
A tuple created using range() function is:
 (5, 15, 25, 35, 45, 55)
A tuple created from a list is:
 (0, 100, 200, 300, 400)
A tuple created by concatenating two tuples is:
 (0, 100, 200, 300, 400, 5, 15, 25, 35, 45, 55)

##Accessing Tuple Elements##
Elements of tuple are also accessed using the concept of indexing and slicing. Indexing and slicing are done in the similar way as lists as demonstrated in the following example:

In [6]:
# Program to access items of a heterogeneous tuple
mytuple7 = (-74.16, 135, "INDIA", "CHINA", ("JAVA", "C", "PYTHON"), "a632", -125, "USA")

# Using a for loop to display the first four elements of the tuple
for val in range(0, 4):
    print("The tuple element", val + 1, "is:", mytuple7[val])

# Accessing individual items of a nested tuple
print("First item of the nested tuple is:", mytuple7[4][0])
print("Second item of the nested tuple is:", mytuple7[4][1])
print("Third item of the nested tuple is:", mytuple7[4][2])

# Indexing and Slicing in Tuple
print("Elements from second to before the fourth index:", mytuple7[1:3])
print("Elements from negative index -3 to index 2:", mytuple7[-3:2])
print("Elements from the start to before the second index:", mytuple7[:2])
print("Elements from the fifth index to the last index:", mytuple7[4:])
print("Elements from the sixth index to the last index:", mytuple7[5:])

# Starting from higher to a lower index (reverse slice)
print("Reversed elements from the fourth to the second index:", mytuple7[3:1:-1])

The tuple element 1 is: -74.16
The tuple element 2 is: 135
The tuple element 3 is: INDIA
The tuple element 4 is: CHINA
First item of the nested tuple is: JAVA
Second item of the nested tuple is: C
Third item of the nested tuple is: PYTHON
Elements from second to before the fourth index: (135, 'INDIA')
Elements from negative index -3 to index 2: ()
Elements from the start to before the second index: (-74.16, 135)
Elements from the fifth index to the last index: (('JAVA', 'C', 'PYTHON'), 'a632', -125, 'USA')
Elements from the sixth index to the last index: ('a632', -125, 'USA')
Reversed elements from the fourth to the second index: ('CHINA', 'INDIA')

##**Functions for Tuple**
- Tuples are immutable, meaning their elements cannot be modified, unlike lists which are mutable.
- All non-modifying functions that apply to lists can also be performed on tuples.
- Functions related to modification (like append(), clear(), extend(), insert(), remove(), and pop()) do not work on tuples.

In [8]:
# Program demonstrating utility functions for tuple
mytuple8 = (310, 150, 300, 450, 220, 350, 357, 505, 375, 200, 150, 350, 150, 460)

# The sum() function returns the sum of all elements of the tuple
print("Sum of all elements in the tuple is:", sum(mytuple8))

# The max() function determines the maximum number in a tuple
print("Maximum number in the tuple is:", max(mytuple8))

# The min() function determines the minimum number in a tuple
print("Minimum number in the tuple is:", min(mytuple8))

# The len() function determines the length of the tuple
print("Length of the tuple is:", len(mytuple8))

# The count() function returns the number of times an element appears in the tuple
print("Number of times 150 occurred in the tuple is:", mytuple8.count(150))

# The index() function returns the lowest index of an element within the tuple
print("First position of element 300 in the tuple:", mytuple8.index(300))

# The sorted() function sorts elements in ascending order without modifying the tuple
print("Sorted tuple without modifying the original tuple is:\n", sorted(mytuple8))

Sum of all elements in the tuple is: 4327
Maximum number in the tuple is: 505
Minimum number in the tuple is: 150
Length of the tuple is: 14
Number of times 150 occurred in the tuple is: 3
First position of element 300 in the tuple: 2
Sorted tuple without modifying the original tuple is:
 [150, 150, 150, 200, 220, 300, 310, 350, 350, 357, 375, 450, 460, 505]

Repetition and checking for an item's existence in a tuple work similarly to lists. Use the * symbol for repetition and the in operator to check for an element, as shown in the example below:

In [7]:
# Program for repetition ("*") and determining existence ("in") in a tuple

# Creating and repeating tuple directly in the print statement
print("Repetition of tuple:\n", (100, 200, 300, 400) * 3)

# Creating a tuple and then repeating the tuple in the print statement
mytuple9 = (10, 20, 30)
print("Repetition of an existing tuple:\n", mytuple9 * 4)

# Repetition of tuple and then using print statement for displaying
newtuple = mytuple9 * 3
print("Displaying the tuple formed after repetition:\n", newtuple)

# Using "in" to determine the existence/non-existence of an item in the tuple
print("The element 12 exists in the new tuple:", (12 in newtuple))
print("The element 30 exists in the new tuple:", (30 in newtuple))

Repetition of tuple:
 (100, 200, 300, 400, 100, 200, 300, 400, 100, 200, 300, 400)
Repetition of an existing tuple:
 (10, 20, 30, 10, 20, 30, 10, 20, 30, 10, 20, 30)
Displaying the tuple formed after repetition:
 (10, 20, 30, 10, 20, 30, 10, 20, 30)
The element 12 exists in the new tuple: False
The element 30 exists in the new tuple: True

##**Dictionary**
- Dictionary: A unique data structure in Python not typically found in other languages, often called the "king of data structures" due to its versatility as a mapping type.
- Mutable: Like lists, dictionaries are mutable, meaning their contents can be modified.
- Unordered Collection: Dictionaries are not necessarily ordered, unlike lists and tuples which are ordered.
- Key-Value Pairs: Dictionaries store data as key-value pairs, where each key maps to a specific value.
- Dictionary Objects: They have three main objects—keys, values, and items—that provide different views of dictionary entries, and these views change as the dictionary is updated.
- Keys and Values: The first element in each pair is the key, and the second is its corresponding value.
- Hashable Keys: Keys in a dictionary must be hashable (e.g., strings, numbers), and they must be unique, while values can be of any type.

###**Creating a Dictionary**
- List and Tuple Creation: Lists use square brackets [], and tuples use parentheses ().
- Dictionary Creation: Dictionaries use curly braces {} or the dict() function.

In [9]:
# Program to create a dictionary in five different ways

# Creating Dictionary through the first approach
mydict1 = dict({'country': 'India', 'capital': 'New Delhi'})
print("Creating Dictionary through the first approach:\n", mydict1)

# Creating Dictionary through the second approach
mydict2 = {'country': 'India', 'capital': 'New Delhi'}
print("Creating Dictionary through the second approach:\n", mydict2)

# Creating Dictionary through the third approach
mydict3 = dict(country='India', capital='New Delhi')
print("Creating Dictionary through the third approach:\n", mydict3)

# Creating Dictionary through the fourth approach
mydict4 = dict([('country', 'India'), ('capital', 'New Delhi')])
print("Creating Dictionary through the fourth approach:\n", mydict4)

# Creating Dictionary through the fifth approach
mydict5 = dict(zip(['country', 'capital'], ['India', 'New Delhi']))
print("Creating Dictionary through the fifth approach:\n", mydict5)

# Determine whether all five methods create the same dictionary
print("Do all methods create the same dictionary:", mydict1 == mydict2 == mydict3 == mydict4 == mydict5)

Creating Dictionary through the first approach:
 {'country': 'India', 'capital': 'New Delhi'}
Creating Dictionary through the second approach:
 {'country': 'India', 'capital': 'New Delhi'}
Creating Dictionary through the third approach:
 {'country': 'India', 'capital': 'New Delhi'}
Creating Dictionary through the fourth approach:
 {'country': 'India', 'capital': 'New Delhi'}
Creating Dictionary through the fifth approach:
 {'country': 'India', 'capital': 'New Delhi'}
Do all methods create the same dictionary: True

You can also create a dictionary using the dict(), zip(), and range() functions, as shown in the example below:

In [10]:
# Program to create a dictionary using range() function
mydict6 = dict(zip('INDIA', range(5)))
print(mydict6)

{'I': 3, 'N': 1, 'D': 2, 'A': 4}

###**Accessing Dictionary Elements**
- No Indexing/Slicing: Unlike lists and tuples, dictionaries do not support indexing and slicing.
- items() Function: Returns all key–value pairs in the dictionary.
- keys() Function: Returns all the keys in the dictionary.
- values() Function: Returns all the values in the dictionary.
- Accessing Values: Access dictionary values by placing the key name inside square brackets.

In [12]:
# Program for accessing dictionary elements
book_dict = {
    'name': 'Data Analytics Using Python',
    'author': 'Dr. Bharti Motwani',
    'publisher': 'Wiley'
}

# Displaying the keys in the dictionary
print("Keys in the dictionary are:\n", book_dict.keys())

# Displaying the values in the dictionary
print("Values in the dictionary are:\n", book_dict.values())

# Displaying the key-value pairs in the dictionary
print("Key-value pairs in the dictionary are:\n", book_dict.items())

# Displaying the values with respect to specified keys
print("Name of the book is:", book_dict['name'])
print("Author is:", book_dict['author'])
print("Publisher is:", book_dict['publisher'])

Keys in the dictionary are:
 dict_keys(['name', 'author', 'publisher'])
Values in the dictionary are:
 dict_values(['Data Analytics Using Python', 'Dr. Bharti Motwani', 'Wiley'])
Key-value pairs in the dictionary are:
 dict_items([('name', 'Data Analytics Using Python'), ('author', 'Dr. Bharti Motwani'), ('publisher', 'Wiley')])
Name of the book is: Data Analytics Using Python
Author is: Dr. Bharti Motwani
Publisher is: Wiley

###**Functions for Dictionary**
- Adding Key-Value Pairs: New key-value pairs can be added to a dictionary in various ways.
- Modifying Values: Existing values associated with keys can also be modified.
- Dictionary Functions: Several functions are available for performing operations on dictionaries, including:
  - len(): Returns the number of items in the dictionary.
  - clear(): Removes all items from the dictionary.
  - pop(): Removes a specified key and returns its value.
  - get(): Retrieves the value associated with a specified key.
  - sorted(): Returns a sorted list of the dictionary’s keys.
  - copy(): Creates a shallow copy of the dictionary.

In [11]:
# Program for using functions for dictionary.

# Addition of new key-value pair to dictionary using first approach.
book_dict = {'address': 'Pune'}

# Addition of new key-value pair to dictionary using second approach.
book_dict.update({'gender': 'Female'})

# Addition of new key-value pair to dictionary using third approach.
book_dict.setdefault('qualification', 'Sh. D.')

# Displaying the dictionary after adding new key-value pairs.
print("Key-value pairs after adding new pairs:\n", book_dict.items())

# Modification in value of key named "address".
book_dict['address'] = 'India'
print("Key-value pairs after modification are:\n", book_dict.items())

# The get() function is used to fetch the value of specified key.
print("Value of qualification key is:", book_dict.get('qualification'))

# The len() function is used to determine the length of the dictionary.
print("Length of the dictionary is:", len(book_dict))

# The sorted() function is used to sort keys in alphabetical order.
print("Sorted list of keys:", sorted(book_dict))

# The pop() function is used to remove a particular key.
print("Using pop() to remove gender key:", book_dict.pop("gender"))
print("Key-value pairs after pop() are:\n", book_dict.items())

# The copy() function to copy a dictionary to another dictionary.
newbook_dict = book_dict.copy()
print("Key-value pairs in new dictionary are:\n", newbook_dict.items())

# The clear() function clears the contents of a dictionary.
newbook_dict.clear()
print("Key-value pairs after clear() are:", newbook_dict)

# To determine the existence of a key in the dictionary.
print("Does 'address' key exist in dictionary?", 'address' in book_dict)
print("Does 'age' key exist in dictionary?", 'age' in book_dict)

Key-value pairs after adding new pairs:
 dict_items([('address', 'Pune'), ('gender', 'Female'), ('qualification', 'Sh. D.')])
Key-value pairs after modification are:
 dict_items([('address', 'India'), ('gender', 'Female'), ('qualification', 'Sh. D.')])
Value of qualification key is: Sh. D.
Length of the dictionary is: 3
Sorted list of keys: ['address', 'gender', 'qualification']
Using pop() to remove gender key: Female
Key-value pairs after pop() are:
 dict_items([('address', 'India'), ('qualification', 'Sh. D.')])
Key-value pairs in new dictionary are:
 dict_items([('address', 'India'), ('qualification', 'Sh. D.')])
Key-value pairs after clear() are: {}
Does 'address' key exist in dictionary? True
Does 'age' key exist in dictionary? False